package net.jonbell.crochet.transform;

import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.MethodNode;

import java.util.ArrayList;
import java.util.List;

/**
 * Class visitor that wraps methods annotated with
 * {@code @net.jonbell.crochet.annotation.CrochetCheckpoint} in a
 * checkpoint / rollback pair.
 *
 * <h2>Generated bytecode shape</h2>
 * For a method {@code void foo(@CrochetRoot Object root, ...)} the emitted code
 * is:
 * <pre>
 *   int v = Crochet.checkpoint(root);
 *   try {
 *       // original body
 *   } catch (Throwable t) {
 *       Crochet.rollback(root, v);
 *       throw t;
 *   }
 *   // on normal return: rollback is called just before each RETURN opcode
 * </pre>
 *
 * <h2>Slot allocation (no LVS)</h2>
 * {@code CheckpointWrapper} sits <em>above</em> {@link SharedLocalsProvider}
 * (the sole {@code LocalVariablesSorter} in the chain), so it cannot call
 * {@code newLocal()}.  Instead it uses deterministic slots above the original
 * method's {@code maxLocals}:
 * <ul>
 *   <li>{@code vSlot = node.maxLocals}      — the {@code int v} version token
 *   <li>{@code retSlot = vSlot + 1}         — saved return value (non-void)
 *   <li>{@code retSlot+1}                   — high word for long/double
 * </ul>
 * Using {@code node.maxLocals} (rather than just {@code paramSlotCount}) avoids
 * collision with compiler-allocated locals such as exception variables in inner
 * {@code catch} blocks.
 *
 * <h2>Two-pass design (ScanMV → WrapMV)</h2>
 * {@link ScanMV} buffers the entire method into an ASM {@link MethodNode} and
 * collects annotation data.  On {@code visitEnd()} it either replays through
 * {@link WrapMV} (annotated) or delegates raw (not annotated).  This avoids
 * the need to know annotation state before seeing method instructions.
 *
 * <h2>Exception-table ordering</h2>
 * The JVM searches the exception table in order; the FIRST matching entry wins.
 * Inner try/catch blocks must therefore appear BEFORE the outer catch-Throwable
 * in the exception table, or they would be preempted.  {@link WrapMV} buffers
 * all inner {@code visitTryCatchBlock} calls and defers flushing them (and then
 * appending the outer entry) to the first real instruction emitted after
 * {@code visitCode()}.
 *
 * <h2>Constraints</h2>
 * Methods that are {@code static}, {@code abstract}, or {@code native} are
 * skipped silently (the APT processor raises compile-time errors for those).
 * Methods with no {@code @CrochetRoot} parameter are likewise skipped.
 */
public final class CheckpointWrapper extends ClassVisitor {

    // Internal name of the Crochet facade (INVOKESTATIC target).
    static final String CROCHET_OWNER = "net/jonbell/crochet/runtime/Crochet";
    static final String CHECKPOINT_DESC = "(Ljava/lang/Object;)I";
    static final String ROLLBACK_DESC = "(Ljava/lang/Object;I)V";

    // Annotation descriptors.
    private static final String CHECKPOINT_ANN =
            "Lnet/jonbell/crochet/annotation/CrochetCheckpoint;";
    private static final String ROOT_ANN =
            "Lnet/jonbell/crochet/annotation/CrochetRoot;";

    public CheckpointWrapper(int api, ClassVisitor next) {
        super(api, next);
    }

    @Override
    public MethodVisitor visitMethod(int access, String name, String descriptor,
                                     String signature, String[] exceptions) {
        MethodVisitor next = super.visitMethod(access, name, descriptor, signature, exceptions);
        // Skip static, abstract, and native — they cannot be wrapped.
        boolean isStatic   = (access & Opcodes.ACC_STATIC)   != 0;
        boolean isAbstract = (access & Opcodes.ACC_ABSTRACT)  != 0;
        boolean isNative   = (access & Opcodes.ACC_NATIVE)    != 0;
        if (isStatic || isAbstract || isNative) {
            return next;
        }
        return new ScanMV(api, next, access, descriptor);
    }

    // -----------------------------------------------------------------------
    // ScanMV: buffers the method and scans for @CrochetCheckpoint / @CrochetRoot
    // -----------------------------------------------------------------------

    /**
     * Buffers the entire method into a {@link MethodNode}, simultaneously
     * scanning for {@code @CrochetCheckpoint} and {@code @CrochetRoot}.
     * On {@code visitEnd()} it replays through {@link WrapMV} or the raw
     * delegate based on whether both annotations were found.
     */
    private static final class ScanMV extends MethodVisitor {

        private final MethodVisitor realDelegate;
        private final int access;
        private final String descriptor;
        private final MethodNode node;

        private boolean hasCheckpointAnn = false;
        // Index (0-based) of the @CrochetRoot parameter; -1 = not found.
        private int rootParamIndex = -1;

        ScanMV(int api, MethodVisitor delegate, int access, String descriptor) {
            // Send all visitation to the MethodNode buffer.
            super(api, null);
            this.realDelegate = delegate;
            this.access = access;
            this.descriptor = descriptor;
            this.node = new MethodNode(api, access, /*name*/ null, descriptor, null, null);
            this.mv = this.node;
        }

        @Override
        public AnnotationVisitor visitAnnotation(String desc, boolean visible) {
            if (CHECKPOINT_ANN.equals(desc)) {
                hasCheckpointAnn = true;
            }
            return node.visitAnnotation(desc, visible);
        }

        @Override
        public AnnotationVisitor visitParameterAnnotation(int parameter, String desc,
                                                          boolean visible) {
            if (ROOT_ANN.equals(desc)) {
                rootParamIndex = parameter;
            }
            return node.visitParameterAnnotation(parameter, desc, visible);
        }

        @Override
        public void visitEnd() {
            node.visitEnd();
            if (!hasCheckpointAnn || rootParamIndex < 0) {
                // Not annotated — replay raw.
                node.accept(realDelegate);
                return;
            }
            // Compute the slot of the @CrochetRoot parameter.
            Type[] argTypes = Type.getArgumentTypes(descriptor);
            // Slot 0 = "this" (non-static method).
            int rootSlot = 1;
            for (int i = 0; i < rootParamIndex; i++) {
                rootSlot += argTypes[i].getSize();
            }
            // Allocate scratch slots ABOVE the original method's max local slot.
            // We cannot use SharedLocalsProvider.newLocal() because CheckpointWrapper
            // sits above it in the chain.  Using fixed slots above paramSlotCount is
            // wrong when the original method has inner try/catch blocks that introduce
            // additional locals (e.g. the exception variable in "catch (Foo e)").
            // Those compiler-allocated locals collide with our vSlot/retSlot if they
            // share the same slot index.  Using node.maxLocals (the actual maximum
            // local count from the original bytecode) guarantees no collision.
            int baseSlot = Math.max(node.maxLocals, 1); // defensive minimum
            int vSlot = baseSlot;
            int retSlot = baseSlot + 1;

            Type returnType = Type.getReturnType(descriptor);
            WrapMV wrap = new WrapMV(api, realDelegate, rootSlot, vSlot, retSlot, returnType);
            node.accept(wrap);
        }
    }

    // -----------------------------------------------------------------------
    // WrapMV: emits the checkpoint/rollback wrapper around the original body
    // -----------------------------------------------------------------------

    /** Helper record to buffer a single try/catch block during replay. */
    private record TcbEntry(Label start, Label end, Label handler, String type) {}

    /**
     * Emits:
     * <ol>
     *   <li>A try/catch(Throwable) block covering the original body.
     *   <li>A {@code Crochet.checkpoint(root)} call at entry, result stored in
     *       {@code vSlot}.
     *   <li>Interception of every {@code xRETURN} opcode: save the return value
     *       in {@code retSlot}, call rollback, reload return value, then return.
     *   <li>An exception handler that calls rollback then re-throws.
     * </ol>
     *
     * <p><b>Exception-table order:</b> inner try/catch blocks (from the original
     * method body) are buffered and flushed to the delegate BEFORE the outer
     * catch-Throwable, so that inner handlers take priority for their covered
     * ranges.
     */
    private static final class WrapMV extends MethodVisitor {

        private final int rootSlot;
        private final int vSlot;
        private final int retSlot;
        private final Type returnType;

        private final Label tryStart = new Label();
        private final Label tryEnd   = new Label();
        private final Label handler  = new Label();

        // Buffered inner try/catch blocks — flushed in order on first instruction.
        private final List<TcbEntry> pendingTcbs = new ArrayList<>();
        // True once the inner TCBs have been flushed.
        private boolean tcbsFlushed = false;

        WrapMV(int api, MethodVisitor next,
               int rootSlot, int vSlot, int retSlot, Type returnType) {
            super(api, next);
            this.rootSlot   = rootSlot;
            this.vSlot      = vSlot;
            this.retSlot    = retSlot;
            this.returnType = returnType;
        }

        @Override
        public void visitTryCatchBlock(Label start, Label end, Label handler, String type) {
            // Buffer inner TCBs; they will be flushed BEFORE the outer catch-all
            // so that they take priority in the exception table.
            pendingTcbs.add(new TcbEntry(start, end, handler, type));
        }

        @Override
        public void visitCode() {
            super.visitCode();
            // Checkpoint call: int v = Crochet.checkpoint(root);
            // The try block MUST start AFTER the ISTORE so that the exception
            // handler frame's local-variable map includes vSlot=int.  If tryStart
            // were placed before the ISTORE, ASM COMPUTE_FRAMES would infer the
            // handler frame without vSlot (because at try-start vSlot is still
            // uninitialized) and the subsequent ILOAD vSlot inside emitRollback
            // would produce a VerifyError.
            super.visitVarInsn(Opcodes.ALOAD, rootSlot);
            super.visitMethodInsn(Opcodes.INVOKESTATIC,
                    CROCHET_OWNER, "checkpoint", CHECKPOINT_DESC, false);
            super.visitVarInsn(Opcodes.ISTORE, vSlot);
            // Mark try start AFTER vSlot is initialised.
            super.visitLabel(tryStart);
        }

        /** Flush inner TCBs then the outer catch-all before the first instruction. */
        private void flushTcbsIfNeeded() {
            if (tcbsFlushed) return;
            tcbsFlushed = true;
            // Inner TCBs first — they must appear before the outer in the table.
            for (TcbEntry tcb : pendingTcbs) {
                super.visitTryCatchBlock(tcb.start(), tcb.end(), tcb.handler(), tcb.type());
            }
            // Outer catch-Throwable last — it is a fallback for anything not
            // caught by the inner handlers.
            super.visitTryCatchBlock(tryStart, tryEnd, handler, null);
        }

        // Override every instruction-emitting visit* to flush TCBs on first call.
        @Override public void visitLabel(Label label) {
            flushTcbsIfNeeded(); super.visitLabel(label);
        }
        @Override public void visitInsn(int opcode) {
            flushTcbsIfNeeded();
            switch (opcode) {
                case Opcodes.RETURN -> {
                    emitRollback();
                    super.visitInsn(Opcodes.RETURN);
                }
                case Opcodes.IRETURN, Opcodes.FRETURN, Opcodes.ARETURN -> {
                    super.visitVarInsn(storeOpcodeFor(opcode), retSlot);
                    emitRollback();
                    super.visitVarInsn(loadOpcodeFor(opcode), retSlot);
                    super.visitInsn(opcode);
                }
                case Opcodes.LRETURN, Opcodes.DRETURN -> {
                    super.visitVarInsn(storeOpcodeFor(opcode), retSlot);
                    emitRollback();
                    super.visitVarInsn(loadOpcodeFor(opcode), retSlot);
                    super.visitInsn(opcode);
                }
                default -> super.visitInsn(opcode);
            }
        }
        @Override public void visitVarInsn(int opcode, int var) {
            flushTcbsIfNeeded(); super.visitVarInsn(opcode, var);
        }
        @Override public void visitIntInsn(int opcode, int operand) {
            flushTcbsIfNeeded(); super.visitIntInsn(opcode, operand);
        }
        @Override public void visitTypeInsn(int opcode, String type) {
            flushTcbsIfNeeded(); super.visitTypeInsn(opcode, type);
        }
        @Override public void visitFieldInsn(int opcode, String owner, String name, String descriptor) {
            flushTcbsIfNeeded(); super.visitFieldInsn(opcode, owner, name, descriptor);
        }
        @Override public void visitMethodInsn(int opcode, String owner, String name,
                                              String descriptor, boolean isInterface) {
            flushTcbsIfNeeded(); super.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
        }
        @Override public void visitJumpInsn(int opcode, Label label) {
            flushTcbsIfNeeded(); super.visitJumpInsn(opcode, label);
        }
        @Override public void visitLdcInsn(Object value) {
            flushTcbsIfNeeded(); super.visitLdcInsn(value);
        }
        @Override public void visitIincInsn(int varIndex, int increment) {
            flushTcbsIfNeeded(); super.visitIincInsn(varIndex, increment);
        }
        @Override public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) {
            flushTcbsIfNeeded(); super.visitTableSwitchInsn(min, max, dflt, labels);
        }
        @Override public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) {
            flushTcbsIfNeeded(); super.visitLookupSwitchInsn(dflt, keys, labels);
        }
        @Override public void visitMultiANewArrayInsn(String descriptor, int numDimensions) {
            flushTcbsIfNeeded(); super.visitMultiANewArrayInsn(descriptor, numDimensions);
        }
        @Override public void visitInvokeDynamicInsn(String name, String descriptor,
                                                     org.objectweb.asm.Handle bootstrapMethodHandle,
                                                     Object... bootstrapMethodArguments) {
            flushTcbsIfNeeded(); super.visitInvokeDynamicInsn(name, descriptor, bootstrapMethodHandle, bootstrapMethodArguments);
        }

        @Override
        public void visitMaxs(int maxStack, int maxLocals) {
            // Ensure TCBs are flushed even for methods with no instructions
            // (shouldn't happen in practice but defensive).
            flushTcbsIfNeeded();
            // Try-end label and handler must be emitted AFTER all original code.
            super.visitLabel(tryEnd);
            // Exception handler: rollback then re-throw.
            super.visitLabel(handler);
            emitRollback();
            super.visitInsn(Opcodes.ATHROW);
            // Let ASM recompute stack/locals with COMPUTE_FRAMES.
            super.visitMaxs(maxStack, maxLocals);
        }

        // Emit: Crochet.rollback(root, v);
        private void emitRollback() {
            super.visitVarInsn(Opcodes.ALOAD, rootSlot);
            super.visitVarInsn(Opcodes.ILOAD, vSlot);
            super.visitMethodInsn(Opcodes.INVOKESTATIC,
                    CROCHET_OWNER, "rollback", ROLLBACK_DESC, false);
        }

        // Map xRETURN → xSTORE
        private static int storeOpcodeFor(int returnOpcode) {
            return switch (returnOpcode) {
                case Opcodes.IRETURN -> Opcodes.ISTORE;
                case Opcodes.LRETURN -> Opcodes.LSTORE;
                case Opcodes.FRETURN -> Opcodes.FSTORE;
                case Opcodes.DRETURN -> Opcodes.DSTORE;
                case Opcodes.ARETURN -> Opcodes.ASTORE;
                default -> throw new AssertionError("not a return opcode: " + returnOpcode);
            };
        }

        // Map xRETURN → xLOAD
        private static int loadOpcodeFor(int returnOpcode) {
            return switch (returnOpcode) {
                case Opcodes.IRETURN -> Opcodes.ILOAD;
                case Opcodes.LRETURN -> Opcodes.LLOAD;
                case Opcodes.FRETURN -> Opcodes.FLOAD;
                case Opcodes.DRETURN -> Opcodes.DLOAD;
                case Opcodes.ARETURN -> Opcodes.ALOAD;
                default -> throw new AssertionError("not a return opcode: " + returnOpcode);
            };
        }
    }
}
